spring:
  application:
    name: currency-exchange-service-prac  datasource:    url: jdbc:mysql://localhost:3306/jsonexample?useSSL=false
    username: root
    password:   jpa:
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true    hibernate:      ddl-auto: update
    show-sql: true
eureka:  client:    service-url:      default-zone: http://localhost:8761/eureka    
server:  port: 8000